### ISSUE TITLE
Can you update package in npm registry?

### ISSUE THREAD

**Issue by mateossh** [mrpotatoes/docsify-toc#8]
You merged PRs, but didn't publish those changes to npm. Can you bump version and do it?

**Comment by mrpotatoes** [comment]
I never set that up so I'll do it manually tonight.

**Comment by mateossh** [comment]
Great! Thank you so much

**Comment by mrpotatoes** [comment]
I spaced but I published it just now. It's `@1.1.0` now. Cheers!
